In [1]:
import numpy as np
import pandas as pd
import astropy.units as u
import astropy.constants as const

In [42]:
file_path = "co.dat.txt"
df_energy = pd.read_csv(file_path, delim_whitespace=True, skiprows=7, nrows=41, header=None, names=["Level", "Energy (cm^-1)", "Weight", "J"])
# # Read Radiative Transitions (Rows 145-185, assuming it starts at row 145)
df_radiative = pd.read_csv(file_path, delim_whitespace=True, skiprows=51, nrows=40, header=None,names=["Transition", "Upper Level", "Lower Level", "Einstein A (s^-1)", "Frequency (GHz)", "E_u (K)"])
# Read Collisional Transitions (Rows 187+)
df_collisional = pd.read_csv(file_path, delim_whitespace=True, skiprows=102, nrows=819,names=['Trans+','Up+','Low+','2.0','5.0','10.0','20.0','30.0','40.0','50.0','60.0','70.0','80.0','90.0','100.0','150.0','200.0','300.0','400.0','500.0','600.0','700.0','750.0','800.0','900.0','1000.0','2000.0','3000.0'], header=None)
df10K = df_collisional[['Trans+','Up+','Low+','10.0']].loc[0:45]
df10K

C:\Users\Prerana Kottapalli\AppData\Local\Temp\ipykernel_18048\3811392733.py:2: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df_energy = pd.read_csv(file_path, delim_whitespace=True, skiprows=7, nrows=41, header=None, names=["Level", "Energy (cm^-1)", "Weight", "J"])
C:\Users\Prerana Kottapalli\AppData\Local\Temp\ipykernel_18048\3811392733.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df_radiative = pd.read_csv(file_path, delim_whitespace=True, skiprows=51, nrows=40, header=None,names=["Transition", "Upper Level", "Lower Level", "Einstein A (s^-1)", "Frequency (GHz)", "E_u (K)"])
C:\Users\Prerana Kottapalli\AppData\Local\Temp\ipykernel_18048\3811392733.py:6: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df_collisional = pd.read_csv(file_path, delim_whitespace=True, skiprows=102, nrows=819,names=['Trans+','Up+','Low+','2.0','5.0','10.0','20.0','30.0','40.0','50.0','60.0','70.0','80.0','90.0','100.0','150.0','200.0','300.0','400.0','500.0','600.0','700.0','750.0','800.0','900.0','1000.0','2000.0','3000.0'], header=None)

    Trans+  Up+  Low+          10.0
0        1    2     1  3.302000e-11
1        2    3     1  3.015000e-11
2        3    3     2  7.150000e-11
3        4    4     1  5.162000e-12
4        5    4     2  5.011000e-11
5        6    4     3  7.946000e-11
6        7    5     1  3.113000e-12
7        8    5     2  9.553000e-12
8        9    5     3  6.229000e-11
9       10    5     4  8.114000e-11
10      11    6     1  9.698000e-13
11      12    6     2  6.220000e-12
12      13    6     3  1.251000e-11
13      14    6     4  7.616000e-11
14      15    6     5  6.553000e-11
15      16    7     1  5.021000e-13
16      17    7     2  2.232000e-12
17      18    7     3  8.923000e-12
18      19    7     4  1.669000e-11
19      20    7     5  8.551000e-11
20      21    7     6  5.799000e-11
21      22    8     1  2.367000e-13
22      23    8     2  1.077000e-12
23      24    8     3  3.604000e-12
24      25    8     4  1.137000e-11
25      26    8     5  2.186000e-11
26      27    8     6  8.990000e-11
27      28    8     7  5.807000e-11
28      29    9     1  9.953000e-14
29      30    9     2  5.491000e-13
30      31    9     3  1.624000e-12
31      32    9     4  5.268000e-12
32      33    9     5  1.336000e-11
33      34    9     6  2.764000e-11
34      35    9     7  9.046000e-11
35      36    9     8  6.315000e-11
36      37   10     1  5.022000e-14
37      38   10     2  2.213000e-13
38      39   10     3  8.934000e-13
39      40   10     4  2.188000e-12
40      41   10     5  7.199000e-12
41      42   10     6  1.471000e-11
42      43   10     7  3.401000e-11
43      44   10     8  8.697000e-11
44      45   10     9  7.198000e-11
45      46   11     1  2.037000e-14

In [58]:
cdr = df10K.loc[df10K['Up+']-df10K['Low+']==1]['10.0']
df10K.loc[df10K['Up+']-df10K['Low+']==1]

    Trans+  Up+  Low+          10.0
0        1    2     1  3.302000e-11
2        3    3     2  7.150000e-11
5        6    4     3  7.946000e-11
9       10    5     4  8.114000e-11
14      15    6     5  6.553000e-11
20      21    7     6  5.799000e-11
27      28    8     7  5.807000e-11
35      36    9     8  6.315000e-11
44      45   10     9  7.198000e-11

In [59]:
eins = df_radiative.loc[0:8]['Einstein A (s^-1)']
df_radiative.loc[0:8]

,Transition,Upper Level,Lower Level,Einstein A (s^-1),Frequency (GHz),E_u (K)
0,1,2,1,7.203000e-08,115.271202,5.53
1,2,3,2,6.910000e-07,230.538000,16.60
2,3,4,3,2.497000e-06,345.795990,33.19
3,4,5,4,6.126000e-06,461.040768,55.32
4,5,6,5,1.221000e-05,576.267931,82.97
5,6,7,6,2.137000e-05,691.473076,116.16
6,7,8,7,3.422000e-05,806.651806,154.87
7,8,9,8,5.134000e-05,921.799700,199.11
8,9,10,9,7.330000e-05,1036.912393,248.88

In [69]:
eins

0    7.203000e-08
1    6.910000e-07
2    2.497000e-06
3    6.126000e-06
4    1.221000e-05
5    2.137000e-05
6    3.422000e-05
7    5.134000e-05
8    7.330000e-05
Name: Einstein A (s^-1), dtype: float64

In [70]:
n_crit = eins.values/cdr.values

In [ ]:
n=100/(u.cm**3)
mach=10
sigma2 = np.log(1+(0.75*mach**2))
def mass_frac(n):